### ISSUE TITLE
Cannot install a new app to my DAO 

### ISSUE THREAD

**Issue by jctaillandier** [aragon/aragon-apps#1423]
Trying to add address-book to my DAO
```
dao install <dao address> address-book.aragonpm.eth --environment rinkeby
```
keeps returning the same error regarding truffle.js file not being present
```
~/.nvm/versions/node/v12.22.8/lib/node_modules/@aragon/cli/src/helpers/truffle-config.js:22
  throw new Error(`Didn't find any truffle.js file`)
        ^
Error: Didn't find any truffle.js file
    at getTruffleConfig (~/.nvm/versions/node/v12.22.8/lib/node_modules/@aragon/cli/src/helpers/truffle-config.js:22:9)
    at configCliMiddleware (~/.nvm/versions/node/v12.22.8/lib/node_modules/@aragon/cli/src/middleware/index.js:58:31)
    at ~/.nvm/versions/node/v12.22.8/lib/node_modules/@aragon/cli/node_modules/yargs/build/lib/middleware.js:48:28
    at Array.reduce (<anonymous>)
    at Object.applyMiddleware (~/.nvm/versions/node/v12.22.8/lib/node_modules/@aragon/cli/node_modules/yargs/build/lib/middleware.js:38:10)
    at Object.runCommand (~/.nvm/versions/node/v12.22.8/lib/node_modules/@aragon/cli/node_modules/yargs/build/lib/command.js:190:38)
    at Object.parseArgs [as _parseArgs] (~/.nvm/versions/node/v12.22.8/lib/node_modules/@aragon/cli/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.runCommand (~.nvm/versions/node/v12.22.8/lib/node_modules/@aragon/cli/node_modules/yargs/build/lib/command.js:157:36)
    at Object.parseArgs [as _parseArgs] (~/.nvm/versions/node/v12.22.8/lib/node_modules/@aragon/cli/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (~/.nvm/versions/node/v12.22.8/lib/node_modules/@aragon/cli/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.argv (~/.nvm/versions/node/v12.22.8/lib/node_modules/@aragon/cli/src/index.js:4:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```
It's true that the path to `helpers/truffle.js` doesnt exists:
```
> ls ~/.nvm/versions/node/v12.22.8/lib/node_modules/@aragon/cli/
aliases  config  dist  LICENSE  node_modules  package.json  schemas
```

Worth mentioning: node versioning issues, where `yarn` required v14, but I could only install aragon with `node v12`.

But also where is supposed to be this truffle.js file and what should be in it? I did follow the [app building guide](https://github.com/aragon/your-first-aragon-app).

**Comment by jctaillandier** [comment]
I copied `truffle.js` from `./dao-templates/templates/bare/truffle.js` and it seems to work.

Is this expected? Why isn't truffle.js not included in each app sub-folder in this project ?
