### ISSUE TITLE
Lerna Failure While Running Tests?

### ISSUE THREAD

**Issue by aunyks** [aragon/aragon-apps#558]
Hi all, I've been having trouble running tests using Lerna and was wondering if there's any insight here.

**Node**: v8.0.0
**NPM**: v6.4.1
**Lerna**: v3.4.3
**Yarn** (same problem): v1.7.0
```
$> npm install && npm run test

> @aragon/monorepo-apps@1.0.0 install /Users/aunyks/dev/aragon
> npm run bootstrap


> @aragon/monorepo-apps@1.0.0 bootstrap /Users/aunyks/dev/aragon
> lerna bootstrap --nohoist=@aragon/os

lerna info version 2.11.0
lerna info versioning independent
lerna info Bootstrapping 9 packages
lerna info lifecycle preinstall
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna info lifecycle prepare
lerna success Bootstrapped 9 packages
up to date in 38.825s

> @aragon/monorepo-apps@1.0.0 test /Users/aunyks/dev/aragon
> npm run test:all


> @aragon/monorepo-apps@1.0.0 test:all /Users/aunyks/dev/aragon
> lerna run --scope=@aragon/apps-* --concurrency=1 --stream test

lerna info version 2.11.0
lerna info versioning independent
lerna info scope @aragon/apps-*
lerna ERR! EPACKAGES Errored while collecting packages and package graph
lerna ERR! TypeError: Cannot read property 'split' of undefined
lerna ERR!     at Minimatch.match (/Users/aunyks/dev/aragon/node_modules/minimatch/minimatch.js:717:8)
lerna ERR!     at minimatch (/Users/aunyks/dev/aragon/node_modules/minimatch/minimatch.js:107:42)
lerna ERR!     at /Users/aunyks/dev/aragon/node_modules/lerna/lib/PackageUtilities.js:84:36
lerna ERR!     at Array.some (native)
lerna ERR!     at filterPackage (/Users/aunyks/dev/aragon/node_modules/lerna/lib/PackageUtilities.js:83:18)
lerna ERR!     at /Users/aunyks/dev/aragon/node_modules/lerna/lib/PackageUtilities.js:248:18
lerna ERR!     at Array.filter (native)
lerna ERR!     at Function.filterPackages (/Users/aunyks/dev/aragon/node_modules/lerna/lib/PackageUtilities.js:247:29)
lerna ERR!     at RunCommand.runPreparations (/Users/aunyks/dev/aragon/node_modules/lerna/lib/Command.js:333:60)
{ TypeError: Cannot read property 'split' of undefined
    at Minimatch.match (/Users/aunyks/dev/aragon/node_modules/minimatch/minimatch.js:717:8)
    at minimatch (/Users/aunyks/dev/aragon/node_modules/minimatch/minimatch.js:107:42)
    at /Users/aunyks/dev/aragon/node_modules/lerna/lib/PackageUtilities.js:84:36
    at Array.some (native)
    at filterPackage (/Users/aunyks/dev/aragon/node_modules/lerna/lib/PackageUtilities.js:83:18)
    at /Users/aunyks/dev/aragon/node_modules/lerna/lib/PackageUtilities.js:248:18
    at Array.filter (native)
    at Function.filterPackages (/Users/aunyks/dev/aragon/node_modules/lerna/lib/PackageUtilities.js:247:29)
    at RunCommand.runPreparations (/Users/aunyks/dev/aragon/node_modules/lerna/lib/Command.js:333:60)
    at /Users/aunyks/dev/aragon/node_modules/lerna/lib/Command.js:209:18 exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aragon/monorepo-apps@1.0.0 test:all: `lerna run --scope=@aragon/apps-* --concurrency=1 --stream test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @aragon/monorepo-apps@1.0.0 test:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aunyks/.npm/_logs/2018-11-01T14_15_20_733Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aragon/monorepo-apps@1.0.0 test: `npm run test:all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @aragon/monorepo-apps@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aunyks/.npm/_logs/2018-11-01T14_15_20_756Z-debug.log
```

**Comment by sohkai** [comment]
It could be that you're on node 8 (suggested is 8.9+, or a newer LTS). On node 10 and macOS 10.14, `npm run test:all` starts the tests for me.

**Comment by sohkai** [comment]
Weird... what if you try `npm run test:voting` or one of the other test scripts?

**Comment by aunyks** [comment]
Yea it happens in every app (including `payroll`) that I try to test.

**Comment by sohkai** [comment]
Really weird :(. What if you go into the apps' directories themselves and try to run `npm run test`?

Wonder if it might also be something related to lerna being installed globally? We're using 2.11.0 (and that's what getting installed and run from the scripts), but maybe having lerna 3.4.3 confuses it?

**Comment by aunyks** [comment]
After removing my global installation of Lerna, the tests still fait from the root directory, but `cd`-ing into each app, installing modules, and running tests works successfully.

**Comment by aunyks** [comment]
Closing because this works all the sudden 🤷‍♂️

**Comment by sohkai** [comment]
Hmm, maybe there was a hidden dependency that got bumped in the last day or so causing this. Maybe the one time a lock file would've saved some hassle.
