### ISSUE TITLE
npm install not working properly after cloning this repo

### ISSUE THREAD

**Issue by sepu85** [aragon/aragon-apps#840]
I've been trying to use this [script](https://github.com/aragon/aragon-apps/blob/master/apps/voting/scripts/vote-stats.js)

after cloning this repo locally and running `npm i` I got the following error:

```npm WARN tar ENOENT: no such file or directory, lstat '/home/sepu85/Aragon/aragon-apps/apps/finance/node_modules/.staging/date-fns-5f79672e/toDate'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

lerna ERR! npm install exited 1 in '@aragon/apps-finance'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aragon/monorepo-apps@1.0.0 bootstrap: `lerna bootstrap --nohoist=@aragon/os`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @aragon/monorepo-apps@1.0.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sepu85/.npm/_logs/2019-05-10T14_14_21_678Z-debug.log
child_process.js:656
    throw err;
    ^

Error: Command failed: npm run bootstrap
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at Object.<anonymous> (/home/sepu85/Aragon/aragon-apps/scripts/install:10:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aragon/monorepo-apps@1.0.0 install: `node scripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @aragon/monorepo-apps@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sepu85/.npm/_logs/2019-05-10T14_14_24_818Z-debug.log
```

**Comment by sepu85** [comment]
[2019-05-10T14_14_21_678Z-debug.log](https://github.com/aragon/aragon-apps/files/3166907/2019-05-10T14_14_21_678Z-debug.log)
[2019-05-10T14_14_24_818Z-debug.log](https://github.com/aragon/aragon-apps/files/3166908/2019-05-10T14_14_24_818Z-debug.log)

**Comment by sohkai** [comment]
@sepu85 Are you still having this issue? It's a bit odd, since it doesn't seem to be a problem for most people :(

**Comment by sepu85** [comment]
Oh!!! Nope! I forgot I left it open... Sorry.
Closing it.

**Comment by chunxi** [comment]
I was getting the same thing.
Try `yarn install`! It worked for me!

**Comment by sohkai** [comment]
Oh boy haha, `yarn` used to have its own set of problems with `web3.js` and we ended up moving away from it because of this :(. Maybe this is fixed now?

**Comment by cgewecke** [comment]
Ran into this today using both npm and yarn on:
```
OSX HighSierra
Node 10.15.3 (npm v6.4.1) (nvm)
```

The following worked for me 
```shell
nvm use 8
yarn install # <-- Yarn, not NPM. 

# Because Lerna crashes downloading go-ipfs, run.... 
npm install -g @aragon/cli@nightly
aragon ipfs install
npm uninstall -g @aragon/cli # Lerna doesn't want you to already have this? Idk. 

npm install # <-- use NPM, not Yarn lol.
```
